var searchData=
[
  ['c_5f',['C_',['../classCCC_1_1StateSpaceModel.html#aeae9c5ee147c753fcf6b28bf12c67085',1,'CCC::StateSpaceModel']]],
  ['calcdiscmatrix',['calcDiscMatrix',['../classCCC_1_1StateSpaceModel.html#a7e1064166faa7edbab396a66ccc79564',1,'CCC::StateSpaceModel']]],
  ['calcgain',['calcGain',['../classCCC_1_1PreviewControl.html#a6fb0138bf23d4daef5a57fb9e2e66c6c',1,'CCC::PreviewControl']]],
  ['calcoptimalinput',['calcOptimalInput',['../classCCC_1_1PreviewControl.html#aca003780b5f9b7f2b44cc47a217355ef',1,'CCC::PreviewControl']]],
  ['calcrunningcostderiv',['calcRunningCostDeriv',['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#ab91194a4c78ae89622d10d3421b1cc99',1,'CCC::DdpCentroidal::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u) const override'],['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#aaf3d400031d6bbd6c52bcb53d895dcd6',1,'CCC::DdpCentroidal::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u, Eigen::Ref&lt; StateStateDimMatrix &gt; running_cost_deriv_xx, Eigen::Ref&lt; InputInputDimMatrix &gt; running_cost_deriv_uu, Eigen::Ref&lt; StateInputDimMatrix &gt; running_cost_deriv_xu) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a206eb6672d8d0bd6b68d4f5036008d2f',1,'CCC::DdpZmp::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a30685c32c9853c09c0561383de03ba24',1,'CCC::DdpZmp::DdpProblem::calcRunningCostDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateDimVector &gt; running_cost_deriv_x, Eigen::Ref&lt; InputDimVector &gt; running_cost_deriv_u, Eigen::Ref&lt; StateStateDimMatrix &gt; running_cost_deriv_xx, Eigen::Ref&lt; InputInputDimMatrix &gt; running_cost_deriv_uu, Eigen::Ref&lt; StateInputDimMatrix &gt; running_cost_deriv_xu) const override']]],
  ['calcstateeqderiv',['calcStateEqDeriv',['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#a42771cb9a802c653e6c56300b8cb6d9f',1,'CCC::DdpCentroidal::DdpProblem::calcStateEqDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateStateDimMatrix &gt; state_eq_deriv_x, Eigen::Ref&lt; StateInputDimMatrix &gt; state_eq_deriv_u) const override'],['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#ad3d69c8d8717f5deef4d9c24d683905b',1,'CCC::DdpCentroidal::DdpProblem::calcStateEqDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateStateDimMatrix &gt; state_eq_deriv_x, Eigen::Ref&lt; StateInputDimMatrix &gt; state_eq_deriv_u, std::vector&lt; StateStateDimMatrix &gt; &amp;state_eq_deriv_xx, std::vector&lt; InputInputDimMatrix &gt; &amp;state_eq_deriv_uu, std::vector&lt; StateInputDimMatrix &gt; &amp;state_eq_deriv_xu) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#aa41bf0f198f29a99c314aa0fb101acfc',1,'CCC::DdpZmp::DdpProblem::calcStateEqDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateStateDimMatrix &gt; state_eq_deriv_x, Eigen::Ref&lt; StateInputDimMatrix &gt; state_eq_deriv_u) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a3985b6b77f9997c79dad57fb82f1af08',1,'CCC::DdpZmp::DdpProblem::calcStateEqDeriv(double t, const StateDimVector &amp;x, const InputDimVector &amp;u, Eigen::Ref&lt; StateStateDimMatrix &gt; state_eq_deriv_x, Eigen::Ref&lt; StateInputDimMatrix &gt; state_eq_deriv_u, std::vector&lt; StateStateDimMatrix &gt; &amp;state_eq_deriv_xx, std::vector&lt; InputInputDimMatrix &gt; &amp;state_eq_deriv_uu, std::vector&lt; StateInputDimMatrix &gt; &amp;state_eq_deriv_xu) const override']]],
  ['calcterminalcostderiv',['calcTerminalCostDeriv',['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#a14a3c93d79ed3ff82412d5614838c88c',1,'CCC::DdpCentroidal::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x) const override'],['../classCCC_1_1DdpCentroidal_1_1DdpProblem.html#a51325489a090a74aded19909d9b5662a',1,'CCC::DdpCentroidal::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x, Eigen::Ref&lt; StateStateDimMatrix &gt; terminal_cost_deriv_xx) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#a5912c17c8b54b1bd9ac9fab88bb2a228',1,'CCC::DdpZmp::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x) const override'],['../classCCC_1_1DdpZmp_1_1DdpProblem.html#aea40eac30d7a5c37718185630072cb61',1,'CCC::DdpZmp::DdpProblem::calcTerminalCostDeriv(double t, const StateDimVector &amp;x, Eigen::Ref&lt; StateDimVector &gt; terminal_cost_deriv_x, Eigen::Ref&lt; StateStateDimMatrix &gt; terminal_cost_deriv_xx) const override']]],
  ['calctotalwrench',['calcTotalWrench',['../structCCC_1_1DdpCentroidal_1_1MotionParam.html#a41e93c15bf5b8cc3b116eb2701d905b1',1,'CCC::DdpCentroidal::MotionParam']]],
  ['capture_5fpoint',['capture_point',['../structCCC_1_1IntrinsicallyStableMpc1d_1_1InitialParam.html#aab05173f77d0d4d3883d6d854b898710',1,'CCC::IntrinsicallyStableMpc1d::InitialParam::capture_point()'],['../structCCC_1_1IntrinsicallyStableMpc_1_1InitialParam.html#a7ef7f4e94863f4120111b5ee81a37b98',1,'CCC::IntrinsicallyStableMpc::InitialParam::capture_point()']]],
  ['ccc',['CCC',['../namespaceCCC.html',1,'']]],
  ['com_5fjerk',['com_jerk',['../structCCC_1_1PreviewControlZmp1d_1_1WeightParam.html#a34141be401bb9cda2f1504baf280d47a',1,'CCC::PreviewControlZmp1d::WeightParam']]],
  ['com_5fz',['com_z',['../structCCC_1_1DdpZmp_1_1RefData.html#a898dc4279152c649a8e91360ca144baa',1,'CCC::DdpZmp::RefData::com_z()'],['../structCCC_1_1LinearMpcXY_1_1MotionParam.html#adc8fa47723dd81a795f567dbf25ebc70',1,'CCC::LinearMpcXY::MotionParam::com_z()']]],
  ['commonmodels_2eh',['CommonModels.h',['../CommonModels_8h.html',1,'']]],
  ['comzmpmodeljerkinput',['ComZmpModelJerkInput',['../classCCC_1_1ComZmpModelJerkInput.html',1,'CCC::ComZmpModelJerkInput'],['../classCCC_1_1ComZmpModelJerkInput.html#a1065720d8ecb366e66714739e04ac292',1,'CCC::ComZmpModelJerkInput::ComZmpModelJerkInput()']]],
  ['constants',['constants',['../namespaceCCC_1_1constants.html',1,'CCC']]],
  ['constants_2eh',['Constants.h',['../Constants_8h.html',1,'']]],
  ['contact',['contact',['../structCCC_1_1LinearMpcZ_1_1MotionData.html#a931ea735faadd354dd0e3f09bf57b5a2',1,'CCC::LinearMpcZ::MotionData']]],
  ['current_5fzmp',['current_zmp',['../structCCC_1_1DcmTracking_1_1RefData.html#a1bac9e05508defbed237e58b34da2cf2',1,'CCC::DcmTracking::RefData']]]
];
