name: Docker release

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'

jobs:

  build-docker:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: ${{ github.repository_owner }}/baseline_walking_controller
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: BaselineWalkingController
      - name: Docker version
        run: docker version
      - name: Build docker image
        run: |
          cd ${GITHUB_WORKSPACE}/BaselineWalkingController/.github/workflows/
          docker build -t ${IMAGE_NAME}:${{ github.sha }} --build-arg REPOSITORY=${{ github.repository_owner }} --build-arg COMMIT_SHA=${{ github.sha }} .
      - name: Docker images
        run: docker images
      - name: Login to registries
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Save image for CI
        run: |
          mkdir /tmp/image
          docker save ${IMAGE_NAME}:${{ github.sha }} -o /tmp/image/${{ github.repository_owner }}-baseline_walking_controller-image.tar
      - name: Upload image for CI
        uses: actions/upload-artifact@v3
        with:
          name: BWC-docker-image
          path: /tmp/image
      - name: Push image for release
        if: github.repository_owner == 'isri-aist' && github.ref == 'refs/heads/master'
        run: |
          docker tag ${IMAGE_NAME}:${{ github.sha }} ghcr.io/${IMAGE_NAME}:latest
          docker push ghcr.io/${IMAGE_NAME}:latest

  test-docker:
    needs: build-docker
    strategy:
      fail-fast: false
      matrix:
        mpc-method: [PreviewControlZmp, DdpZmp, FootGuidedControl, IntrinsicallyStableMpc]
        mpc-framework: [OnlineMpc, OfflineMpc]
        motion-type: [WalkingOnPlane, WalkingOnStairs]
        include:
          - mpc-method: PreviewControlZmp
            mpc-framework: OfflineMpc
            motion-type: WalkingWithFootstepPlanner
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: ${{ github.repository_owner }}/baseline_walking_controller
      RESULTS_POSTFIX: ${{ matrix.mpc-method }}-${{ matrix.mpc-framework }}-${{ matrix.motion-type }}
    steps:
      - name: Download image for CI
        uses: actions/download-artifact@v3
        with:
          name: BWC-docker-image
          path: /tmp/image
      - name: Load image for CI
        run: |
           docker load -i /tmp/image/${{ github.repository_owner }}-baseline_walking_controller-image.tar
           docker images
      - name: Run test on image
        run: |
           docker run --env MPC_METHOD=${{ matrix.mpc-method }} --env MPC_FRAMEWORK=${{ matrix.mpc-framework }} --env MOTION_TYPE=${{ matrix.motion-type }} --env RESULTS_POSTFIX=${RESULTS_POSTFIX} ${IMAGE_NAME}:${{ github.sha }} /root/catkin_ws/src/BaselineWalkingController/.github/workflows/scripts/test_docker.bash
      # - name: Upload simulation data
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: BWC-docker-results
      #     path: /tmp/results
